[server]
headless = true
runOnSave = true
port = 8501
enableCORS = false

[theme]
base = "light"
primaryColor = "#4CAF50"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[client]
showSidebarNavigation=true